config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "game/:difficulty", to: "pages#home", as: "game"

  get "/log_in", to: "sessions#new"
  post "/log_in", to: "sessions#create"
  delete "/log_out", to: "sessions#destroy"

  get "/sign_up", to: "users#new"
  post "/sign_up", to: "users#create"

  get "/profile", to: "users#show", as: "user"
  delete "/profiles/:id", to: "users#destroy", as: "user_destroy"

  get "/scoreboard", to: "plays#index", as: "plays"

  post "/plays/:difficulty/:is_win/:time_in_seconds", to: "plays#create"
  post "/plays/update", to: "plays#update"

  match '*unmatched', to: 'pages#not_found', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/play.rb
class Play < ApplicationRecord
  has_one :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays

  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  def check_user_logged_in
    redirect_to "/" unless session[:user_id].present?
  end

  def check_user_not_logged_in
    redirect_to "/" unless session[:user_id].nil?
  end  

  private

  def fetch_user
    @current_user = User.find_by(:id => session[:user_id]) if session[:user_id].present?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def home
    if params[:difficulty].present? && ["easy", "medium", "hard"].include?(params[:difficulty].downcase)
      @difficulty = params[:difficulty]
    else  
      @difficulty = "medium"
    end  
  end 
  
  def not_found
  end  
end 

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  include ApplicationHelper
  skip_before_action :verify_authenticity_token, only: [:create, :update]
  
  def index
    @easy_plays = get_and_order_displayable_plays(filter_plays_by_difficulty(Play.all, "easy"))
    @medium_plays = get_and_order_displayable_plays(filter_plays_by_difficulty(Play.all, "medium"))
    @hard_plays = get_and_order_displayable_plays(filter_plays_by_difficulty(Play.all, "hard"))
    if @easy_plays.empty? && @medium_plays.empty? && @hard_plays.empty?
      @intro_text = "No times have been submitted yet."
    elsif
      @intro_text = "The top scoring plays are the successful plays with the shortest times."  
    end    
  end

  def create
    puts "Add Play"
    user = fetch_user
    unless user.nil? 
      play = Play.create(play_params)   
      play.user_id = user.id
      play.save
    end
  end

  def update
    play = Play.last
    play.is_publicly_displayed = true
    play.save
  end  
  
  private

  def play_params
    params.permit(:difficulty, :is_win,:time_in_seconds)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_user_logged_in, only: [:delete]
  before_action :check_user_not_logged_in, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    return unless is_login_valid? user
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end

  private

  def is_login_valid? user
    unless user.present? && user.authenticate(params[:password])
      flash[:error] = "Error: Incorrect Username or Password"
      redirect_to "/log_in"
      return false
    end  
    return true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :check_user_logged_in, only: [:show]
  before_action :check_user_not_logged_in, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    return unless is_user_valid?
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    end  
  end

  def show
    @user = user
    easy_plays = filter_plays_by_difficulty(user.plays, "easy")
    medium_plays = filter_plays_by_difficulty(user.plays, "medium")
    hard_plays = filter_plays_by_difficulty(user.plays, "hard")
    @easy_win_percentage = get_win_percentage(easy_plays)
    @medium_win_percentage = get_win_percentage(medium_plays)
    @hard_win_percentage = get_win_percentage(hard_plays)
    @displayed_easy_plays = get_and_order_winning_plays(easy_plays)
    @displayed_medium_plays = get_and_order_winning_plays(medium_plays)
    @displayed_hard_plays = get_and_order_winning_plays(hard_plays)
    @win_count = win_count
  end

  private

  def show_error error
    flash[:error] = error 
    redirect_to "/sign_up"
  end

  def is_user_valid?
    usernames = User.all.map{|user| user.username}
    emails = User.all.map{|user| user.email}
    if usernames.include?(user_params[:username])
      show_error "Error: Username Must Be Unique" 
      return false
    elsif emails.include?(user_params[:email])
      show_error "Error: Email Must Be Unique"
      return false
    elsif user_params[:password] != user_params[:password_confirmation]
      show_error "Error: Password Confirmation Must Match Password" 
      return false
    end    
    return true
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def user
    User.find(@current_user.id)
  end

  def get_all_winning_plays(plays)
    plays.filter{ |play| play.is_win }
  end 

  def get_win_percentage(plays)
    unless plays.count == 0
      (get_all_winning_plays(plays).count * 100 / plays.count).round(2)
    end
  end

  def win_count
    user.plays.filter(&:is_win).count
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_time(time)
    time.localtime.strftime("%-l:%M:%S%P %d/%m/%Y")
  end  

  def convert_time_to_date(time)
    time.localtime.strftime("%d/%m/%Y")
  end  

  def filter_plays_by_difficulty(plays, difficulty)
    plays.filter{|play| play.difficulty.downcase == difficulty}
  end

  def get_and_order_winning_plays(plays)
    order_and_select_plays(plays.filter(&:is_win))
  end

  def get_and_order_displayable_plays(plays)
    order_and_select_plays(plays.filter{ |play| play.is_win && play.is_publicly_displayed })
  end  

  private

  def order_and_select_plays(plays)
    plays.sort_by(&:time_in_seconds).take(10)
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BombSweeper</title>
    <meta charset="UTF-8">
    <meta name="description" content="A minesweeper clone"> 
    <meta name="viewport" content="width=device-width,initial-scale=1"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path("bomb-favicon.png") %>
  </head>

  <body>
    <%= render partial: "shared/navbar/navbar" %>
    <main class="d-flex flex-column align-items-center w-75 mx-auto my-5 fs-5">
      <%= yield %>
      <div id="root"></div>
    </main>  
    <%= javascript_include_tag "http://localhost:4000/static/js/bundle.js" %>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Instructions</h2>

<section class="w-75 text-center">
  <div class="d-flex flex-column mb-5 text-wrap">
  
    <p>Bombsweeper works just like Minesweeper only with bombs instead of mines and the option to save and track scores :)</p>

    <p>Left click on a square to reveal it. Revealing the first square starts the timer - unless it's a bomb!</p>

    <p>If you reveal a square with a bomb, you lose. If you're logged in, your loss will be stored in the database and will decrease your win percentage for the selected difficulty.</p>

    <p>If the revealed square is safe, it will display the number of (horizontally, vertically and diagonally) adjecent squares with bombs.</p>
    
    <p>If no surrounding squares have bombs, the revealed square will appear blank and the surrounding safe squares will automatically be revealed (triggering a cascade of square reveals).</p>

    <p>If you suspect that an unrevealed square has a bomb, you can right click it to mark it with a flag. Right clicking a flagged square removes the flag.</p>
    
    <p>The flag counter below the board intially specifies the number of bombs on the board and decreases as you add flags to the board. You can place as many flags as you like. A negative counter just means you've placed more flags than there are bombs.</p>

    <p>You can pause the game by clicking the "Pause" button. This will stop the timer, but also hide all of the board's squares so you can't cheat.</p>

    <p>If you manage to reveal all the safe squares, you win the game. The timer will stop and (if you're logged in) your time will be automatically saved to the database. You can view your quickest winning times and win percentages (for each difficulty) on your user profile.</p>

    <p>If you're logged in, a (functional) "Submit Time" button will appear. Click this button to make your time publicly displayable. It will then appear on a public scoreboard (if it is one of the top ten times for the selected difficulty).</p>

    <p>If you wish to play again, click the "Reset" button. You can also click this button during a game. Games that are reset don't count towards your win percentages.</p>

    <p>Enjoy the game!</p>
  </div>  

  <h3>Difficulties</h3>

  <ul class="d-flex justify-content-center mt-4 mb-5 list-unstyled">
    <li class="<%= @difficulty == "easy" ? "selected" : "" %>"><%= link_to "Easy Board", game_path("easy"), class: "btn btn-dark mx-3 px-4 border-0" %></li>
    <li class="<%= @difficulty == "medium" ? "selected" : "" %>"><%= link_to "Medium Board", game_path("medium"), class: "btn btn-dark mx-3 px-4 border-0" %></li>
    <li class="<%= @difficulty == "hard" ? "selected" : "" %>"><%= link_to "Hard Board", game_path("hard"), class: "btn btn-dark mx-3 px-4 border-0" %></li>
  </ul>

  <h3 class="mb-4"><%= @difficulty.capitalize %> Board</h3>
</section>

app/views/pages/not_found.html.erb
<h2>Error: Page Not Found</h2>

<section class="text-center">
<p>Sorry, we couldn't find the page you're looking for</p>

<p>Try using the menu above to navigate to the page you're interested in</p>
</section>

app/views/plays/index.html.erb
<h2>Scoreboard</h2>

<p><%= @intro_text %></p>

<%= render partial: "shared/score_tables/score_tables", locals: { easy_plays: @easy_plays, medium_plays: @medium_plays, hard_plays: @hard_plays, show_user: true } %>

<%= render partial: "shared/home_link" %>

app/views/shared/_account_features_list.html.erb
<ul>
  <li>Track your win percentages</li>
  <li>View your quickest winning times</li>
  <li>Submit your times to the public scoreboard</li>
</ul>

app/views/shared/_home_link.html.erb
<p class="back-link m-0">
  <%= link_to "Back to the Game", root_path, class: "btn btn-dark px-4" %>
</p>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-between p-0">
    <ul class="navbar-nav">
      <li class="nav-item d-flex align-items-center">
        <h1 class="navbar-brand mx-3 my-0">BombSweeper</h1>
      </li>  
      <%= render partial: "shared/navbar_link", locals: { text: "The Game", path: root_path } %>
      <%= render partial: "shared/navbar_link", locals: { text: "Scoreboard", path: plays_path } %>
    </ul>
    <ul class="navbar-nav">
      <% if @current_user.present? %>
        <%= render partial: "shared/navbar_link", locals: { text: "View Profile", path: user_path(@current_user.id)} %>
        <li class="nav-item d-flex align-items-center">
          <%= link_to 'Log Out', log_out_path, data: { turbo_method: :delete }, class: "nav-link" %>
        </li>
      <% else %>  
        <%= render partial: "shared/navbar_link", locals: { text: "Sign Up", path: sign_up_path } %>
        <%= render partial: "shared/navbar_link", locals: { text: "Log In", path: log_in_path } %>
      <% end %>  
    </ul>
  </nav>
</header>

app/views/shared/forms/_form.html.erb
<%= form_with model: model, url: path, class: "mt-4 mb-5" do |form| %>
  <p class="error-message text-center text-danger">
    <% flash.each do |type, message| %>
      <%= message %>
    <% end %>
  </p>

  <% if type == "Sign Up" %>
    <%= render partial: "shared/forms/form_input", locals: { form: form, label: :username, type: "text", placeholder: "Enter a name here ...", required: true, minlength: 8, maxlength: 20 } %>
  <% end %>  
  <%= render partial: "shared/forms/form_input", locals: { form: form, label: :email, type: "email", placeholder: "Enter an email here ...", required: true, minlength: 8, maxlength: 100 } %>
  <%= render partial: "shared/forms/form_input", locals: { form: form, label: :password, type: "password", placeholder: "Enter a password here ...", required: true, minlength: 6, maxlength: 20 } %>
  <% if type == "Sign Up" %>
    <%= render partial: "shared/forms/form_input", locals: { form: form, label: :password_confirmation, type: "password", placeholder: "Enter password again ...", required: true, minlength: 6, maxlength: 20 } %>
  <% end %>

  <div class="d-flex justify-content-center mt-5">
    <%= form.submit type, class: "btn btn-dark" %>
  </div>
<% end %>

<div class="mt-5">
  <%= render partial: "shared/home_link" %>
</div>

app/views/shared/forms/_form_input.html.erb
  <div class="form-group mb-4">
    <%= form.label label, class: "mb-2" %>
    <%= form.text_field label, class: "form-control", type: type, placeholder: placeholder, required: required, minlength: minlength, maxlength: maxlength %>
  </div>

app/views/shared/navbar/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark d-flex justify-content-between p-0">
    <ul class="navbar-nav">
      <li class="nav-item d-flex align-items-center">
        <h1 class="navbar-brand d-flex px-3 mx-0 my-1 text-center">BombSweeper</h1>
      </li>
      <%= render partial: "shared/navbar/navbar_link", locals: { text: "The Game", paths: [ root_path, game_path("easy"), game_path("medium"), game_path("hard") ] } %>
      <%= render partial: "shared/navbar/navbar_link", locals: { text: "Scoreboard", paths: [ plays_path ] } %>
    </ul>
    <ul class="navbar-nav">
      <% if @current_user.present? %>
        <%= render partial: "shared/navbar/navbar_link", locals: { text: "View Profile", paths: [ user_path ] } %>
        <li class="nav-item d-flex align-items-center">
          <%= link_to "Log Out", log_out_path, data: { turbo_method: :delete }, class: "nav-link d-flex align-items-center px-3 text-center" %>
        </li>
      <% else %>
        <%= render partial: "shared/navbar/navbar_link", locals: { text: "Log In", paths: [ log_in_path ] } %>
        <%= render partial: "shared/navbar/navbar_link", locals: { text: "Sign Up", paths: [ sign_up_path ] } %>
      <% end %>  
    </ul>
  </nav>
</header>

app/views/shared/navbar/_navbar_link.html.erb
<li class="nav-item <%= paths.include?(request.fullpath) ? "selected" : "" %>">
  <%= link_to text, paths.first, class: "nav-link d-flex align-items-center px-3 text-center" %>
</li>

app/views/shared/score_tables/_score_table.html.erb
<% unless plays.length == 0 %>
  <h3>Fastest <%= difficulty %> Times</h3>

  <% if win_percentage.present? %>
    <p><span class="fw-bold">Win Percentage:</span> <%= win_percentage %>%</p>
  <% end %>

  <table class="table mt-2 mb-5">
    <thead>
      <tr>
        <% if show_user %>
          <th class="px-4">Username</th>
        <% end %>  
        <th class="px-4">Time</th>
        <th class="px-4">Difficulty</th>
        <th class="px-4 text-nowrap">Achieved At</th>
      </tr>
    </thead>
    <tbody>
      <% plays.map do |play| %>
        <tr>
          <% if show_user %>
            <td class="px-4"><%= User.find(play.user_id).username %></td>
          <% end %>  
          <td class="px-4"><%= play.time_in_seconds %>s</td>
          <td class="px-4"><%= play.difficulty.capitalize %></td>
          <td class="px-4 text-nowrap"><%= convert_time(play.created_at) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/shared/score_tables/_score_tables.html.erb
<% easy_win_percentage ||= nil %>
<% medium_win_percentage ||= nil %>
<% hard_win_percentage ||= nil %>
<% show_user ||= false %>

<section class="mt-4 mb-4 text-center">
  <%= render partial: "shared/score_tables/score_table", locals: {difficulty: "Easy", win_percentage: easy_win_percentage, plays: easy_plays, show_user: show_user} %>
  <%= render partial: "shared/score_tables/score_table", locals: {difficulty: "Medium", win_percentage: medium_win_percentage, plays: medium_plays, show_user: show_user} %>
  <%= render partial: "shared/score_tables/score_table", locals: {difficulty: "Hard", win_percentage: hard_win_percentage, plays: hard_plays, show_user: show_user} %>
</section>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<section class="mt-4">
  <p class="text-center">With a BombSweeper account you can</p>

  <%= render partial: "shared/account_features_list" %>

  <p class="text-center">Sign up today!</p>
</section> 

<%= render partial: "shared/forms/form", locals: { type: "Sign Up", model: @user, path: sign_up_path } %>

app/views/users/show.html.erb
<h2>Hi <%= @user.username %>!</h2>

<section class="details d-flex justify-content-center mb-4">
  <div class="mx-3"><span class="fw-bold">Email:</span> <%= @user.email %></div> 
  <div class="mx-3"><span class="fw-bold">Joined:</span> <%= convert_time_to_date(@user.created_at) %></div>
</section>

<p class="mb-0">You have won <%= @win_count %> <%= "time".pluralize(@win_count) %>. Your quickest winning times are displayed below. </p>

<p class="mb-0">This includes times you did not choose to submit to the public scoreboard.</p>

<%= render partial: "shared/score_tables/score_tables", locals: {easy_win_percentage: @easy_win_percentage, medium_win_percentage: @medium_win_percentage, hard_win_percentage: @hard_win_percentage, easy_plays: @displayed_easy_plays, medium_plays: @displayed_medium_plays, hard_plays: @displayed_hard_plays} %>

<%= render partial: "shared/home_link" %>